### ISSUE TITLE
Alterar senha do usuario

### ISSUE THREAD

**Issue by fbocosta** [MicrosoftDocs/windowsserverdocs.pt-br#3]
Como criar o link para alteração da senha do usuario na versão 1.0.21.0
 ?? 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 94c63e96-2bd1-2406-122e-05f3495a18d9
* Version Independent ID: fdbe3c97-60b6-5c94-a5f8-27b9d8319e66
* Content: [Novidades do cliente Web](https://docs.microsoft.com/pt-br/windows-server/remote/remote-desktop-services/clients/web-client-whatsnew#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/web-client-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs.pt-br/blob/live/WindowsServerDocs/remote/remote-desktop-services/clients/web-client-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by srvbpigh** [comment]
Hello, @fbocosta
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @fbocosta 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/windowsserverdocs/issues/3586

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
