### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by JhonyTY** [MicrosoftDocs/windowsserverdocs.pt-br#5]
Boa tarde, eu gostaria de saber se um host com windows 10 home, não consegue se conectar à um servidor TS?! a licença home o restringe à esse tipo de acesso ? estamos configurando VPN para os usuários atuarem home office, porém a maioria dos notebooks são windows 10 home, hoje testei apenas em um notebook, e não consegui conectar ao TS de jeito nenhum.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9cc647b1-b2a7-7b60-8c34-1718bad72dd0
* Version Independent ID: 73630a01-0734-1d15-dc40-1bde7a34ca4f
* Content: [Cliente de Área de Trabalho Remota - configuração com suporte](https://docs.microsoft.com/pt-br/windows-server/remote/remote-desktop-services/clients/remote-desktop-supported-config#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-supported-config.md](https://github.com/MicrosoftDocs/windowsserverdocs.pt-br/blob/live/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-supported-config.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by srvbpigh** [comment]
Hello, @JhonyTY
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @JhonyTY

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS
