### ISSUE TITLE
Porta para ativação de licença

### ISSUE THREAD

**Issue by dalianelanzarin** [MicrosoftDocs/windowsserverdocs.pt-br#7]
Bom dia, temo um servidor de licença e preciso que 01 jump server busque esta licença, já apontei o IP no regedit, porem preciso liberar a conexão no firewall, saberia me informar qual porta ele usa para esta conexão e ativação da licença?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 4767a747-aab2-11eb-28fc-02652c3479ec
* Version Independent ID: c3245db3-8839-7b41-32a2-b4cf14bc5848
* Content: [Implantar o seu ambiente de Área de Trabalho Remota](https://docs.microsoft.com/pt-br/windows-server/remote/remote-desktop-services/rds-deploy-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs.pt-br/blob/live/WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by srvbpigh** [comment]
Hello, @dalianelanzarin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @dalianelanzarin 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original.
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/windowsserverdocs.pt-br/blob/live/WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente,

Equipe Internacional do Microsoft DOCS
