### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windowsserverdocs.pt-br#8]
When trying to create the virtual machine, without the data disk, an error occurs. Is the data disc optional?
Link showing the error: https://i.imgur.com/GuaNVcN.gifv

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 09578fc1-5b25-a252-cafc-59e753532f2f
* Version Independent ID: 53930633-d16e-fd56-e2ba-a31c2fd33480
* Content: [Implantar máquinas virtuais do Azure usando o centro de administração do Windows](https://docs.microsoft.com/pt-br/windows-server/manage/windows-admin-center/azure/create-azure-vms#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/create-azure-vms.md](https://github.com/MicrosoftDocs/windowsserverdocs.pt-br/blob/live/WindowsServerDocs/manage/windows-admin-center/azure/create-azure-vms.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by srvbpigh** [comment]
Hello, @gabrielluizbh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @gabrielluizbh , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
